import type { MetricEntity } from "./types";

/**
 * METRIC EXTRACTION — every measurable proof point in the resume as a
 * first-class object. Strong metrics never live buried in paragraphs;
 * the compiler places them (hero proof points, chapter headers, cards,
 * globe overlays) by displayPriority.
 */
export const metrics: MetricEntity[] = [
  {
    id: "m-students",
    value: "36,000+",
    label: "students represented",
    context: "Reelected campus-wide as UIC Student Body Vice President.",
    sourceEntityId: "lead-usg",
    confidence: "explicit",
    displayPriority: 1,
  },
  {
    id: "m-orgs",
    value: "460+",
    label: "organizations engaged",
    context: "Student organizations connected with faculty and community.",
    sourceEntityId: "lead-usg",
    confidence: "explicit",
    displayPriority: 3,
  },
  {
    id: "m-policy",
    value: "50,000+",
    label: "people affected by policy",
    context: "Policy shaping across the wider UIC community.",
    sourceEntityId: "lead-usg",
    confidence: "explicit",
    displayPriority: 5,
  },
  {
    id: "m-members",
    value: "60",
    label: "members overseen",
    context: "Decision-making authority within student government.",
    sourceEntityId: "lead-usg",
    confidence: "explicit",
    displayPriority: 9,
  },
  {
    id: "m-growth",
    value: "100%+",
    label: "participation growth",
    context: "Flames Force athletics engagement after launch.",
    sourceEntityId: "lead-flamesforce",
    confidence: "explicit",
    displayPriority: 6,
  },
  {
    id: "m-agencies",
    value: "2,000+",
    label: "tourism agencies",
    context: "Revenue maximized across Istanbul's agency network.",
    sourceEntityId: "exp-mytrip",
    confidence: "explicit",
    displayPriority: 7,
  },
  {
    id: "m-speakers",
    value: "25",
    label: "speakers coordinated",
    context: "osQF conference, as the sole student organizer.",
    sourceEntityId: "conf-osqf",
    confidence: "explicit",
    displayPriority: 10,
  },
  {
    id: "m-guests",
    value: "100+",
    label: "conference guests",
    context: "Industry relationships built through osQF.",
    sourceEntityId: "conf-osqf",
    confidence: "explicit",
    displayPriority: 12,
  },
  {
    id: "m-pmt",
    value: "500+",
    label: "members, alumni & partners",
    context: "People strategy for a student investment organization.",
    sourceEntityId: "lead-pmt",
    confidence: "explicit",
    displayPriority: 8,
  },
  {
    id: "m-sites",
    value: "9",
    label: "major sites visited",
    context: "Hands-on construction management across Dubai.",
    sourceEntityId: "exp-almak",
    confidence: "explicit",
    displayPriority: 13,
  },
  {
    id: "m-students-taught",
    value: "100+",
    label: "students supported",
    context: "Teaching projects in Cape Town and Bali.",
    sourceEntityId: "proj-teaching",
    confidence: "explicit",
    displayPriority: 11,
  },
  {
    id: "m-boards",
    value: "7",
    label: "university boards",
    context: "From fee advisory to the Vice Chancellor search committee.",
    sourceEntityId: "gov-boards",
    confidence: "derived",
    displayPriority: 14,
  },
  {
    id: "m-countries",
    value: "4",
    label: "countries of professional experience",
    context: "United States, Indonesia, the UAE and Türkiye.",
    sourceEntityId: "person-dilay",
    confidence: "derived",
    displayPriority: 4,
  },
];

export const metricById = new Map(metrics.map((m) => [m.id, m]));
