/**
 * Facade kept for module-path stability (nav imports "@/data/chapters").
 * Chapters are generated by the IA generator — see src/content/ia.ts.
 */
export { chapters, chapterById } from "./index";
